categorical_groups: {}
cell_type: GRU
dropout: 0.2
embedding_labels:
  house_hold:
    '0': 1
    nan: 0
embedding_paddings:
- house_hold
embedding_sizes:
  house_hold: !!python/tuple
  - 2
  - 1
hidden_size: 15
learning_rate: 0.1
log_gradient_flow: false
log_interval: -1
log_val_interval: -1
monotone_constaints: {}
optimizer: Ranger
optimizer_params: null
output_size: 1
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:numpy.core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    0nzp6nU+uj8=
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:numpy.core.multiarray.scalar
  - *id001
  - !!binary |
    tsfY9J5Kwj8=
  transformation: null
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
rnn_layers: 2
static_categoricals:
- house_hold
static_reals:
- encoder_length
target: Energy_kwh
target_lags: {}
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder:
- time_idx
time_varying_reals_encoder:
- time_idx
- Energy_kwh
weight_decay: 0.0
x_categoricals:
- house_hold
x_reals:
- encoder_length
- time_idx
- Energy_kwh
